ATEVersions_Management/ATEVersions_Management/Controllers/CPKSystemController.cs
using ATEVersions_Management.Models.CPKModels;
using ATEVersions_Management.Models.DTOModels;
using ATEVersions_Management.Models.DAOModels;
using Syncfusion.XlsIO;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using ATEVersions_Management.Models.ATEVersionModels;

namespace ATEVersions_Management.Controllers
{
    public class CPKSystemController : Controller
    {
        // ====== =================== ======
        //     CPK From Database Section
        // ====== =================== ======
        #region ====== CPK From Database Section ======
        // ====== Handling requests ======
        // GET: CPKSystem Index View
        public ActionResult CPKDBIndex()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }

            List<CPKModelStationContent> modelStationList = CPKTableDAO.GetListCPKModelStation();

            return View(modelStationList);
            
        }

        // GET: CPKSystem model and station item list
        public ActionResult CPKItemList(string model, string station)
        {
            CPKTableDTO cpkRecord = CPKTableDAO.GetOneCPKDataByModelAndStation(model, station);
            CPKModelStationContent cpkModelStation = CPKTableDAO.GetModelStationContent(cpkRecord);
            TempData["CPKData"] = cpkModelStation;
            return View(cpkModelStation);
        }
        // GET: Partial view table CPK model and station item list  
        public ActionResult PartialTableCPKModelStationItem(string model, string station, int pcsNum, string keyMO, string keyPC, DateTime fromDay, DateTime toDay)
        {
            try
            {
                /* DateTime toDay = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, 7, 30, 0),
                    fromDay = toDay.AddDays(-1);*/
                CPKTableDTO cpkRecord = CPKTableDAO.GetOneCPKDataByModelAndStation(model, station);
                List<CPKTableDTO> rawCPKContentList = CPKTableDAO.GetCPKByModelStationDate(model, station, pcsNum, keyMO, keyPC, fromDay, toDay);
                //cpkRecord.CPKContentObjects = CPKTableDAO.GetCPKRecordContentObjectList(cpkRecord.RawContents);
                CPKModelStationContent cpkModelStation = CPKTableDAO.GetModelStationFullContentValue(CPKTableDAO.GetModelStationContent(cpkRecord), rawCPKContentList);
                // ======== Manipulate data section ========
                
                //
                TempData["cpkModelStation"] = cpkModelStation;
                return PartialView(cpkModelStation);
            }
            catch (Exception ex)
            {
                return Json(ex.Message + ":\n"+ex.InnerException,JsonRequestBehavior.AllowGet);
            }
          
        }
        // GET: Draw CPK chart
        public ActionResult CPKDrawing(string model, string station, int? pos, string itemName)
        {
            /*TempData.Keep("CPKData");
            CPKModelStationContent cpkModelStation = (CPKModelStationContent)TempData["CPKData"];*/
            
            ViewBag.ItemName = itemName;
            ViewBag.ModelName = model;
            ViewBag.StationName = station;                        
            ViewBag.Pos = pos;
            return View();
        }
        // GET: Partial view chart drawing section
        public PartialViewResult CPKChartSection(string model, string station, int? pos, int pcsNumber, string moNumber, string atePC, DateTime fromDay, DateTime toDay)
        {

            CPKTableDTO cpkRecord = CPKTableDAO.GetOneCPKDataByModelAndStation(model, station);
            //cpkRecord.CPKContentObjects = CPKTableDAO.GetCPKRecordContentObjectList(cpkRecord.RawContents);
            CPKModelStationContent cpkModelStation = CPKTableDAO.GetModelStationContent(cpkRecord);
            CPKCalculate cpkDrawData = new CPKCalculate();
            if (pos.HasValue)
            {
                //cpkDrawData = GetDataFromDb(cpkModelStation, pos.Value);
                cpkDrawData = GetCPKWithDate(cpkModelStation, pos.Value, pcsNumber, moNumber, atePC, fromDay, toDay);
            }

            return PartialView(cpkDrawData);
        }
        // GET: View data of specific SN
        public ActionResult CPKPcbSNCheck(string model, string station, string pcbSN)
        {

            CPKTableDTO cpkRecord = CPKTableDAO.GetOneCPKDataBySN(model, station, pcbSN);                        

            return View(cpkRecord);
        }
        // GET: View data of model and station
        public ActionResult CPKModelStationData()
        {

            return View();
        }

        // GET: View data of specific item
        public ActionResult CPKItemData(string model, string station, int? pos)
        {

            CPKTableDTO cpkRecord = CPKTableDAO.GetOneCPKDataByModelAndStation(model, station);
            CPKModelStationContent cpkModelStation = CPKTableDAO.GetModelStationContent(cpkRecord);
            CPKCalculate cpkDrawData = new CPKCalculate();
            if (pos.HasValue)
            {
                cpkDrawData = GetDataFromDb(cpkModelStation, pos.Value);
            }
            ViewBag.ModelName = model;
            ViewBag.StationName = station;

            return View(cpkDrawData);
        }

        // Export cpk data to excel
        public void POST_ExportCPKToExcel()
        {
            CPKModelStationContent cpkModelStationContent = TempData["cpkModelStation"] as CPKModelStationContent;
            using (ExcelEngine excelEngine = new ExcelEngine())
            {
                //Initialize Application
                IApplication application = excelEngine.Excel;
                //Set the default application version as Excel 2016
                application.DefaultVersion = ExcelVersion.Excel2016;
                //Create a workbook with a worksheet
                IWorkbook workbook = application.Workbooks.Create(1);
                //Access first worksheet from the workbook instance
                IWorksheet worksheet = workbook.Worksheets[0];
                //Define columns of DataTable 
                DataTable table = new DataTable();
                //Create title columns
                table.Columns.Add("PCB_SN", typeof(string));

                foreach (CPKContentInvidual cpkContent in cpkModelStationContent.ContentGroup)
                {
                    table.Columns.Add(cpkContent.ItemName + " (" + cpkContent.SpecL + "," + cpkContent.SpecH + ")", typeof(string));
                }

                DataColumnCollection cpkDataColumns = table.Columns;

                //Fill data rows to datatable
                int rowNum = cpkModelStationContent.ListPCBSN.Count;
                for (int iRow = 0; iRow <= rowNum; iRow++)
                {
                    DataRow cpkDataRow = table.NewRow();

                    for(int iCol = 0; iCol < cpkDataColumns.Count; iCol++)
                    {
                        if(iRow == 0)
                        {
                            if(iCol == 0)
                            {
                                cpkDataRow[cpkDataColumns[iCol]] = "CPK";
                            }
                            if (iCol > 0)
                            {
                                cpkDataRow[cpkDataColumns[iCol]] = cpkModelStationContent.ContentGroup[iCol - 1].CPKResult.Cpk.ToString();
                            }
                        }
                        else
                        {
                            if (iCol == 0)
                            {
                                cpkDataRow[cpkDataColumns[iCol]] = cpkModelStationContent.ListPCBSN[iRow - 1];
                            }
                            else
                            {
                                cpkDataRow[cpkDataColumns[iCol]] = cpkModelStationContent.ContentGroup[iCol - 1].Value[iRow - 1];
                            }
                        }                        
                    }

                    table.Rows.Add(cpkDataRow);

                }
                
                //import datatable to worksheet
                worksheet.ImportDataTable(table, true, 1, 1);
                worksheet.UsedRange.AutofitColumns();
                //Save the workbook to disk in xlsx format
                string TestName = cpkModelStationContent.ModelName + "_" + cpkModelStationContent.Station + "_CPKData_Exported";
                workbook.SaveAs(TestName + ".xlsx", ExcelSaveType.SaveAsXLS, HttpContext.ApplicationInstance.Response, ExcelDownloadType.Open);
            }

        }

        #region ====== AJAX Calling Functions ======
        [HttpGet]
        public JsonResult GET_CPKOnOffModelList(DateTime fromDate, DateTime toDate)
        {
            try
            {                
                List<string> _cpkOnlineModels = CPKTableDAO.GET_TodayCPKModel(fromDate, toDate);
                List<string> _cpkOfflineModels = CPKTableDAO.GetAllCPKModel().Except( _cpkOnlineModels ).ToList();
                return Json(new {cpkOnlineModels = _cpkOnlineModels, cpkOfflineModels = _cpkOfflineModels }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(ex, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpGet]
        public JsonResult GET_ListCPKModelStation()
        {
            try
            {
                List<CPKModelStationContent> listCPKModelStation = CPKTableDAO.GetListCPKModelStation();
                return Json(listCPKModelStation, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(ex, JsonRequestBehavior.AllowGet);
            }
        }
        
        [HttpGet]
        public JsonResult GET_CPKModelList()

ATEVersions_Management/ATEVersions_Management/Controllers/GRRModuleController.cs
using ATEVersions_Management.Models.DAOModels;
using ATEVersions_Management.Models.DTOModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ATEVersions_Management.Controllers
{
    public class GRRModuleController : Controller
    {
        // GET: GRRModule
        public ActionResult GRRModuleIndex()
        {

            if (User.Identity.IsAuthenticated)
            {
                List<GRRTableDTO> listGRR = ATEVersionsDAO.GetGRRList();
                ViewBag.ErrorMessage = TempData["ErrorMessage"];
                return View(listGRR);
            }
            return RedirectToAction("Login", "Account");
        }
        //GET: GRR Report client view
        //
        public ActionResult GRRModuleDetail(int id)
        {
            GRRTableDTO detailGRR = ATEVersionsDAO.GetGRRByID(id);
            return View(detailGRR);
        }
    }
}

ATEVersions_Management/ATEVersions_Management/Controllers/HomeController.cs
using ATEVersions_Management.Models.ATEVersionModels;
using ATEVersions_Management.Models.HelperModels;
using ATEVersions_Management.Models.DTOModels;
using ATEVersions_Management.Models.DAOModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using Syncfusion.XlsIO;
using System.Data;

namespace ATEVersions_Management.Controllers
{    
    public class HomeController : Controller
    {
        // ====== Connect to database ======
        readonly ATEVersionContext db = new ATEVersionContext();
        //
        // ====== =================== ======

        // ====== Handling requests ======
        
        // Client Index view
        public ActionResult Index()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }            
            ViewBag.Message = TempData["Message"];
            //return RedirectToAction("CltVersionIndex", "ATEVersion");
            return View();
        }

        // About view
        public ActionResult About()
        {
            List<VersionDTO> listCurrentVersion = ATEVersionsDAO.GetVersionList();
            //List<TETestDataDTO> listModelVersion = TETestDataDAO.GetListVersionOfModel();
            Dictionary<string,string> dicLastestModelVer = TETestDataDAO.DictionaryLastestVersionOfModel();
            //ViewBag.ModelVersion = listModelVersion;
            ViewBag.LatestModelVer = dicLastestModelVer;
            List<VersionDTO> ListVersions = ATEVersionsDAO.SetAdditionalVersionsData(listCurrentVersion);
            ViewBag.LatestCurrentModelVer = ListVersions;

            return View();
        }
        // Contact view
        public ActionResult Contact()
        {

            ViewBag.Message = "Contact page.";            

            return View();
        }
        // Error foward view
        public ActionResult Error404Page()
        {
            return View();
        }
        public ActionResult TestLayout()
        {
            return View();
        }
    }
}

ATEVersions_Management/ATEVersions_Management/Controllers/TestPlanController.cs
using ATEVersions_Management.Models.DAOModels;
using ATEVersions_Management.Models.DTOModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ATEVersions_Management.Controllers
{
    public class TestPlanController : Controller
    {
        #region =========== View Controller Functions ===========
        // GET: TestPlan
        public ActionResult CltTestPlanIndex()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            List<TestPlanDTO> listTestPlan = ATEVersionsDAO.GetTestPlanList();
            return View(listTestPlan);
        }
        #endregion

        #region =========== AJAX Calling Functions ===========
        public ActionResult _PartialTestPlanTable(string model)
        {
            try
            {
                List<TestPlanDTO> listTestPlan = ATEVersionsDAO.GetTestPlanByModel(model);
                return PartialView(listTestPlan);
            }
            catch (Exception ex)
            {
                return Json(ex, JsonRequestBehavior.AllowGet);
            }
            
        }
        public JsonResult GET_ListModelOfTestPlan()
        {
            try
            {
                List<string> listModelTestPlan = ATEVersionsDAO.GetListModelOfTestPlan();
                return Json(listModelTestPlan,JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(ex, JsonRequestBehavior.AllowGet);
            }
        }
        public JsonResult GET_ListTestPlanPreview()
        {
            try
            {
                List<TestPlanPreviewDTO> listTestPlanPreview = ATEVersionsDAO.GetListTestPlanPreview();
                return Json(listTestPlanPreview, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(ex, JsonRequestBehavior.AllowGet);
            }
        }
        public JsonResult GET_ListTestPlanPreviewByProjectType(string projectType)
        {
            try
            {
                List<TestPlanPreviewDTO> listTestPlanPreview = ATEVersionsDAO.GET_ListTestPlanPreviewByProjectType(projectType);
                return Json(listTestPlanPreview, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(ex, JsonRequestBehavior.AllowGet);
            }
        }
        #endregion
    }
}

ATEVersions_Management/ATEVersions_Management/Views/Home/About.cshtml
@using ATEVersions_Management.Models.DTOModels  
@{
    ViewBag.Title = "About";
    Layout = "~/Views/Shared/LayoutClient.cshtml";

    //List<TETestDataDTO> listVersionModel = ViewBag.ModelVersion;
    Dictionary<string, string> dicLatestVersionModel = ViewBag.LatestModelVer;
    List<VersionDTO> listVersionDTOs = ViewBag.LatestCurrentModelVer;
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
    
    <hr />
    <div>
        @foreach (var item in dicLatestVersionModel)
        {
            <p> @item.Key | @item.Value </p>
        }
    </div>
    <hr />
    <div>
        @foreach (var item in listVersionDTOs)
        {
            <p> @item.ModelName | @item.VersionName | @item.IsLastest | @item.Usage</p>
        }
    </div>
</main>

ATEVersions_Management/ATEVersions_Management/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/LayoutClient.cshtml";
}

<div class="container">
    <!-- Outer Row -->
    <div class="row justify-content-center">

        <div class="col-xl-4 col-md-9">

            <div class="card o-hidden border-0 shadow-lg my-5">
                <div class="card-header py-3">
                    <h3 class="m-0 font-weight-bold text-primary">@ViewBag.Title</h3>
                </div>
                <div class="card-body p-4">
                    <!-- Nested Row within Card Body -->
                    <address>
                        <h5>
                            Fuyu Precision Technology
                            Quang Chau, Bac Giang.
                        </h5>
                        <strong>Bu:</strong>  JBD<br />
                        <strong>Dept:</strong>  UBEE - F13 - 2F<br />
                        <strong>Pos:</strong> TE<br />
                        <strong>Extension: </strong>535 - 31241 <br />
                        <strong>Email: </strong><a href="#">abel.gx.huang@mail.foxconn.com</a><br />
                    </address>
                </div>
            </div>

        </div>
    </div>
</div>

ATEVersions_Management/ATEVersions_Management/Views/Home/Error404Page.cshtml
@{
    ViewBag.Title = "404";
    Layout = "~/Views/Shared/LayoutClient.cshtml";
}

<!-- 404 Error Text -->
<div class="text-center">
    <div class="error mx-auto" data-text="404">404</div>
    <p class="lead text-gray-800 mb-5">Page Not Found</p>
    <p class="text-gray-500 mb-0">It looks like you did something wrong...</p>
    <a href="@Url.Action("Index", "Home")">
        <i class="fas fa-fw fa-arrow-alt-circle-left"></i>
        <span>Back to home</span>
    </a>
</div>

ATEVersions_Management/ATEVersions_Management/Views/Home/Index.cshtml
@using ATEVersions_Management.Models.DTOModels
@using ATEVersions_Management.Models.HelperModels
@using ATEVersions_Management.Models.ATEVersionModels
@model IEnumerable<VersionDTO>
@{
    ViewBag.Title = "Smart Factory";
    //Layout = "~/Views/Shared/LayoutClient.cshtml";
    Layout = "~/Views/Shared/_LayoutFiiTheme.cshtml";
}

<div class="fii-container-bg h-100 w-100 ">

    <div class="fii-frame-subcontent h-100">
        <!-- begin::index menu items -->
        <div class=" d-flex flex-wrap p-3">
            <div class="fii-frame-index m-1">
                <a class="fii-frame-index-inneritem"
                   href="http://10.220.99.166/SMTDATA" target="_blank">
                    <div class="w-100" align="center">
                        <img class="fii-icon" src="~/Assets/Vendor/fii-template/fii-theme/fii-icon-automation.png" />
                        <div class="fii-title-index fw-bold">

                            <span class="">SMT Data Analysis</span>

                        </div>
                    </div>
                </a>
            </div>
            <div class="fii-frame-index m-1">
                <a class="fii-frame-index-inneritem"
                   href="@Url.Action("CltVersionIndex","ATEVersion")">
                    <div class="w-100" align="center">
                        <img class="fii-icon" src="/Assets/Vendor/fii-template/fii-theme/fii-icon-version.png" />
                        <div class="fii-title-index fw-bold">
                            <span>
                                ATE Program Versions Management
                            </span>
                        </div>
                    </div>
                </a>
            </div>
            <div class="fii-frame-index m-1">
                <a class="fii-frame-index-inneritem"
                   href="@Url.Action("CltTestPlanIndex","TestPlan")">
                    <div class="w-100" align="center">
                        <img class="fii-icon" src="~/Assets/Vendor/fii-template/fii-theme/fii-icon-testplan.png" />
                        <div class="fii-title-index fw-bold">
                            <span>
                                ATE MFG Test Plans Doc Management
                            </span>
                        </div>
                    </div>
                </a>
            </div>
            <div class="fii-frame-index m-1">
                <a class="fii-frame-index-inneritem"
                   href="@Url.Action("EnergySavingIndex","EnergySaving")">
                    <div class="w-100" align="center">
                        <img class="fii-icon" src="~/Assets/Vendor/fii-template/fii-theme/fii-icon-ehs.png" />
                        <div class="fii-title-index fw-bold">
                            <span>
                                ATE Energy Control
                            </span>
                        </div>
                    </div>
                </a>
            </div>
            <div class="fii-frame-index m-1">
                <a class="fii-frame-index-inneritem"
                   href="@Url.Action("ATETimeIndex","TestTimeSystem")">
                    <div class="w-100" align="center">
                        <img class="fii-icon" src="~/Assets/Vendor/fii-template/fii-theme/fii-icon-atetime.png" />
                        <div class="fii-title-index fw-bold">
                            <span>
                                ATE Test Time Analysis
                            </span>
                        </div>
                    </div>
                </a>
            </div>
            <div class="fii-frame-index m-1">
                <a class="fii-frame-index-inneritem"
                   href="@Url.Action("FATPMonitorIndex","FATPMonitor")">
                    <div class="w-100" align="center">
                        <img class="fii-icon" src="~/Assets/Vendor/fii-template/fii-theme/fii-icon-fatp.png" />
                        <div class="fii-title-index fw-bold">

                            <span class="">FATP Status Analysis</span>

                        </div>
                    </div>
                </a>
            </div>
            <div class="fii-frame-index m-1">
                <a class="fii-frame-index-inneritem"
                   href="@Url.Action("CPKDBIndex","CPKSystem")">
                    <div class="w-100" align="center">
                        <img class="fii-icon" src="~/Assets/Vendor/fii-template/fii-theme/fii-icon-cpk.png" />
                        <div class="fii-title-index fw-bold">

                            <span class="">CPK Analyzing System</span>

                        </div>

                    </div>
                </a>
            </div>
            <div class="fii-frame-index m-1">
                <a class="fii-frame-index-inneritem"
                   href="@Url.Action("GRRModuleIndex","GRRModule")">
                    <div class="w-100" align="center">
                        <img class="fii-icon" src="~/Assets/Vendor/fii-template/fii-theme/fii-icon-grr.png" />
                        <div class="fii-title-index fw-bold">

                            <span class="">GR&R Reports</span>

                        </div>
                    </div>
                </a>
            </div>
            <div class="fii-frame-index m-1">
                <a class="fii-frame-index-inneritem"
                   href="@Url.Action("TestTimeIndex","TestTimeSystem")">
                    <div class="w-100" align="center">
                        <img class="fii-icon" src="~/Assets/Vendor/fii-template/fii-theme/fii-icon-estimate.png" />
                        <div class="fii-title-index fw-bold">

                            <span class="">Test Equipment Estimate</span>

                        </div>
                    </div>
                </a>
            </div>
            <div class="fii-frame-index m-1">
                <a class="fii-frame-index-inneritem"
                   href="https://fiisw-cns.myfiinet.com/customer/customer-detail?factory=F16" target="_blank">
                    <div class="w-100" align="center">
                        <img class="fii-icon" src="~/Assets/Vendor/fii-template/fii-theme/fii-icon-product.png" />
                        <div class="fii-title-index fw-bold">

                            <span class="">Tester Reason Analysis</span>

                        </div>
                    </div>
                </a>
            </div>
            <div class="fii-frame-index m-1">
                <a class="fii-frame-index-inneritem"
                   href="https://fiisw-cns.myfiinet.com/paperless/" target="_blank">
                    <div class="w-100" align="center">
                        <img class="fii-icon" src="~/Assets/Vendor/fii-template/fii-theme/fii-icon-paperless.png" />
                        <div class="fii-title-index fw-bold">

                            <span class="">Paperless Checklist Statistic</span>

                        </div>
                    </div>
                </a>
            </div>
            <div class="fii-frame-index m-1">
                <a class="fii-frame-index-inneritem"
                   href="https://fiisw-cns.myfiinet.com/" target="_blank">
                    <div class="w-100" align="center">
                        <img class="fii-icon" src="~/Assets/Vendor/fii-template/fii-theme/fii-icon-hr.png" />
                        <div class="fii-title-index fw-bold">
                            <span class="">Engineer Management</span>
                        </div>
                    </div>
                </a>
            </div>
            <div class="fii-frame-index m-1">
                <a class="fii-frame-index-inneritem indeveloping" data-toggle="modal" data-target="#notifyModal"
                   href="#" target="">
                    <div class="w-100" align="center">
                        <img class="fii-icon" src="~/Assets/Vendor/fii-template/fii-theme/fii-icon-tms.png" />
                        <div class="fii-title-index fw-bold">
                            <span class="">OBA Management System</span>
                        </div>
                    </div>
                </a>
            </div>
            <div class="fii-frame-index m-1">
                <a class="fii-frame-index-inneritem indeveloping" data-toggle="modal" data-target="#notifyModal"
                   href="#" target="">
                    <div class="w-100" align="center">
                        <img class="fii-icon" src="~/Assets/Vendor/fii-template/fii-theme/fii-icon-copyic.png" />
                        <div class="fii-title-index fw-bold">
                            <span class="">Copy IC Management System</span>
                        </div>
                    </div>
                </a>
            </div>
        </div>
        <!-- begin::index menu items -->
    </div>
</div>

<!-- Modal Version List -->
<div class="modal fade " id="notifyModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 id="" class="fw-bold text-blue">
                    
                </h4>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="row modal-body ">
                <h3 class="fw-bold text-center text-info" id="">
                    THIS MODULE IS IN DEVELOPING STAGE!
                </h3>
            </div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>