ATEVersions_Management/ATEVersions_Management/Areas/Admin/Controllers/AdmTestPlanController.cs
using ATEVersions_Management.Models.ATEVersionModels;
using ATEVersions_Management.Models.DAOModels;
using ATEVersions_Management.Models.DTOModels;
using ATEVersions_Management.Models.HelperModels;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace ATEVersions_Management.Areas.Admin.Controllers
{
    public class AdmTestPlanController : DashboardController
    {
        private readonly ATEVersionContext db = new ATEVersionContext();
        // GET: Admin/AdmTestPlan
        public ActionResult TestPlanIndex()
        {
            List<TestPlanDTO> listTestPlan = ATEVersionsDAO.GetTestPlanList();
            return View(listTestPlan);
        }

        // GET: View for creating new test plan infor
        public ActionResult TestPlanCreate()
        {
            ViewBag.listProjectType = new SelectList(ATEVersionsDAO.GET_ListProjectType());
            ViewBag.ListModel = ATEVersionsDAO.GetListATEModel();
            return View();
        }
        // POST: Post action to create new test plan information
        [HttpPost]
        public async Task<ActionResult> TestPlanCreate(TestPlanDTO testPlanDTO) 
        {
            ViewBag.ListModel = ATEVersionsDAO.GetListATEModel();
            if(testPlanDTO.FileUpload == null)
            {
                ViewBag.ErrorMessage = "Must attach a file!";
                return View();
            }
            try
            {
                                
                if(!ATEVersionsDAO.ExistTestPlanVer(testPlanDTO.TestPlanID, testPlanDTO.ModelName, testPlanDTO.TestPlanVersion))
                {
                    // Get data to TEST_PLAN model
                    TEST_PLAN createTestPlan = new TEST_PLAN
                    {
                        UserID = User.Identity.GetUserId(),
                        ModelName = testPlanDTO.ModelName,
                        ProjectType = testPlanDTO.ProjectType,
                        TestPlanVersion = testPlanDTO.TestPlanVersion,
                        Author = testPlanDTO.Author,
                        ModifyNote = testPlanDTO.ModifyNote,
                        ModifiedAt = testPlanDTO.ModifiedAt,
                        StoredDir = TestPlanFileProcess(testPlanDTO.ModelName, testPlanDTO.TestPlanVersion, testPlanDTO.FileUpload),
                        Status = 1,
                        CreatedAt = DateTime.Now,
                        UpdatedAt = DateTime.Now,
                        UpdatedBy = User.Identity.GetUserName() + " | " + User.Identity.GetName(),
                    };
                    // Save data to database
                    db.TEST_PLANs.Add(createTestPlan);
                    await db.SaveChangesAsync();
                    // Finishing up
                    Notification.setFlash1s("Add new test plan " + createTestPlan.ModelName + "_" + createTestPlan.TestPlanVersion + " successfully!", "success");
                    return RedirectToAction("TestPlanIndex");
                }

                Notification.setFlash1s("Test plan " + testPlanDTO.ModelName + "_" + testPlanDTO.TestPlanVersion + " is existed!","danger");
                
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                ViewBag.ErrorMessage = ex.Message;
            }
            
            return View();
        }
        // GET: View for viewing test plan detail information
        public ActionResult TestPlanDetail(int id)
        {            
            TestPlanDTO detailTestPlan = ATEVersionsDAO.GetTestPlanByID(id);
            return View(detailTestPlan);
        }

        // GET: View for editing test plan infor
        public ActionResult TestPlanEdit(int id)
        {
            ViewBag.listProjectType = new SelectList(ATEVersionsDAO.GET_ListProjectType());
            ViewBag.ListUserSameRole = new SelectList(ATEVersionsDAO.GetUserListByRoleID(User.Identity.GetRoleCode()),"UserID","FullName");
            TestPlanDTO editTestPlan = ATEVersionsDAO.GetTestPlanByID(id);
            return View(editTestPlan);
        }
        // POST: Post action to edit test plan information
        [HttpPost]
        public async Task<ActionResult> TestPlanEdit(TestPlanDTO editTestPlanDTO)
        {
            ViewBag.ListUserSameRole = new SelectList(ATEVersionsDAO.GetUserListByRoleID(User.Identity.GetRoleCode()), "UserID", "FullName");            

            try
            {
                // Get edited data to db model
                
                if (!ATEVersionsDAO.ExistTestPlanVer(editTestPlanDTO.TestPlanID, editTestPlanDTO.ModelName, editTestPlanDTO.TestPlanVersion))
                {
                    TEST_PLAN editTestPlan = db.TEST_PLANs.Find(editTestPlanDTO.TestPlanID);
                    editTestPlan.TestPlanVersion = editTestPlanDTO.TestPlanVersion;
                    editTestPlan.UserID = editTestPlanDTO.UserID;
                    editTestPlan.ProjectType = editTestPlanDTO.ProjectType;
                    editTestPlan.Author = editTestPlanDTO.Author;
                    editTestPlan.ModifyNote = editTestPlanDTO.ModifyNote;
                    editTestPlan.ModifiedAt = editTestPlanDTO.ModifiedAt;
                    if(editTestPlanDTO.FileUpload != null)
                    {
                        editTestPlan.StoredDir = TestPlanFileProcess(editTestPlanDTO.ModelName, editTestPlanDTO.TestPlanVersion, editTestPlanDTO.FileUpload);
                    }
                    editTestPlan.UpdatedAt = DateTime.Now;
                    editTestPlan.UpdatedBy = User.Identity.GetUserName() + " | " + User.Identity.GetName();
                    // Save change to database
                    
                    await db.SaveChangesAsync();
                    // Finishing up
                    Notification.setFlash1s("Test plan " + editTestPlan.ModelName + "_" + editTestPlan.TestPlanVersion + " edited successfully!", "success");
                    return RedirectToAction("TestPlanDetail", new { id = editTestPlan.TestPlanID });
                }

                Notification.setFlash1s("Test plan " + editTestPlanDTO.ModelName + "_" + editTestPlanDTO.TestPlanVersion + " is existed!", "danger");
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = ex.Message;
            }

            return View(editTestPlanDTO);
        }
        // POST: Post action to delete test plan
        [HttpPost]
        public async Task<ActionResult> TestPlanDelete(int id)
        {
            try
            {
                TEST_PLAN deleteTestPlan = db.TEST_PLANs.Find(id);
                DeleteFileOnRemovingTestPlan(deleteTestPlan.StoredDir);
                db.TEST_PLANs.Remove(deleteTestPlan);
                // save change to database
                await db.SaveChangesAsync();
            }
            catch (Exception ex)
            {
                Notification.setFlash1s("Error on deleting test plan: " + ex.Message,"danger");
                Console.WriteLine("Error: " + ex);
            }
            return RedirectToAction("TestPlanIndex");
        }

        #region Helper
        private string TestPlanFileProcess(string model, string ver, HttpPostedFileBase testPlanFile)
        {
            try
            {
                // Check directory
                string FormatTestPlanDir = "/Client_Data/TestPlans/" + model + "/";
                string ServerTestPlanDirPath = Server.MapPath("~" + FormatTestPlanDir);
                if (!Directory.Exists(ServerTestPlanDirPath))
                {
                    Directory.CreateDirectory(ServerTestPlanDirPath);
                }
                // Save file to TestPlan folder
                string fileExtension = Path.GetExtension(testPlanFile.FileName);
                string FormatFileName = model + "_Test_Plan_" + ver + fileExtension;
                string SavedFilePath = FormatTestPlanDir + FormatFileName;
                string ServerTestPlanFilePath = Path.Combine(Server.MapPath("~" + SavedFilePath));                
                testPlanFile.SaveAs(ServerTestPlanFilePath);

                return SavedFilePath;
            }
            catch(Exception ex)
            {
                return "Error: " + ex;
            }
            
        }
        private void DeleteFileOnRemovingTestPlan(string filePath)
        {
            // Delete testplan file
            string ServerFilePath = Server.MapPath("~" + filePath);
            if (System.IO.File.Exists(ServerFilePath))
            {
                System.IO.File.Delete(ServerFilePath);
            }
            // Delete testplan folder if empty
            string testplanFolderPath = ServerFilePath.Substring(0, ServerFilePath.LastIndexOf("\\"));
            if(Directory.GetFiles(testplanFolderPath).Length == 0)
            {
                Directory.Delete(testplanFolderPath);
            }            
        }
        #endregion
    }
}

ATEVersions_Management/ATEVersions_Management/Areas/Admin/Views/AdmTestPlan/TestPlanCreate.cshtml
@using ATEVersions_Management.Models.DTOModels
@model TestPlanDTO
@using ATEVersions_Management.Models.HelperModels
@{
    ViewBag.Title = "New Test Plan";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";

    List<string> listModel = ViewBag.ListModel;
    SelectList listProjectType = ViewBag.listProjectType as SelectList;
}


@using (Html.BeginForm("TestPlanCreate", "AdmTestPlan", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal row justify-content-center">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <!--begin::Content -->
        <div class="content d-flex flex-column flex-column-fluid col-md-6">
            <!--begin::Post-->
            <div class="card shadow d-flex flex-column-fluid ">
                <div class="card-header py-3">
                    <h3 class="m-0 font-weight-bold text-primary">New Test Plan</h3>
                </div>
                <!--begin::Card body-->
                <div class="card-body border-top ">
                    <p class="text-danger text-center">@ViewBag.ErrorMessage</p>
                    <!--begin::Input group-->
                    <div class="row justify-content-center mb-2">
                        <!--begin::Label-->
                        <label class="col-sm-3 col-form-label fw-bold fs-6">
                            <span>@Html.DisplayNameFor(model => model.ModelName)</span>
                        </label>
                        <!--end::Label-->
                        <!--begin::Col-->
                        <div class="col-sm-6 fv-row">
                            @Html.EditorFor(model => model.ModelName, new { htmlAttributes = new { @class = "form-select upperText", required = "required", list = "ATEModelList" } })
                            @Html.ValidationMessageFor(model => model.ModelName, "", new { @class = "text-danger" })
                            <datalist id="ATEModelList">
                                @foreach (var item in listModel)
                                {
                                    <option value="@item"></option>
                                }
                            </datalist>
                        </div>
                        <!--end::Col-->
                    </div>
                    <!--end::Input group-->
                    <!--begin::Input group-->
                    <div class="row justify-content-center mb-2">
                        <!--begin::Label-->
                        <label class="col-sm-3 col-form-label fw-bold fs-6">
                            <span>@Html.DisplayNameFor(model => model.TestPlanVersion)</span>
                        </label>
                        <!--end::Label-->
                        <!--begin::Col-->
                        <div class="col-sm-6 fv-row">
                            @Html.EditorFor(model => model.TestPlanVersion, new { htmlAttributes = new { @class = "form-control upperText", Value = "V", required = "required" } })
                            @Html.ValidationMessageFor(model => model.TestPlanVersion, "", new { @class = "text-danger" })
                        </div>
                        <!--end::Col-->
                    </div>
                    <!--end::Input group-->
                    <!--begin::Input group-->
                    <div class="row justify-content-center mb-2">
                        <!--begin::Label-->
                        <label class="col-sm-3 col-form-label fw-bold fs-6">
                            <span>@Html.DisplayNameFor(model => model.ProjectType)</span>
                        </label>
                        <!--end::Label-->
                        <!--begin::Col-->
                        <div class="col-sm-6 fv-row">
                            @Html.DropDownListFor(model => model.ProjectType, listProjectType, "--- Select type ---", htmlAttributes: new { @class = "form-select", @id = "" })
                            @Html.ValidationMessageFor(model => model.ProjectType, "", new { @class = "text-danger" })
                        </div>
                        <!--end::Col-->
                    </div>
                    <!--end::Input group-->
                    <!--begin::Input group-->
                    <div class="row justify-content-center mb-2">
                        <!--begin::Label-->
                        <label class="col-sm-3 col-form-label fw-bold fs-6">
                            <span>@Html.DisplayNameFor(model => model.Author)</span>
                        </label>
                        <!--end::Label-->
                        <!--begin::Col-->
                        <div class="col-sm-6 fv-row">
                            @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control", Value = "", required = "required" } })
                            @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
                        </div>
                        <!--end::Col-->
                    </div>
                    <!--end::Input group-->
                    <!--begin::Input group-->
                    <div class="row justify-content-center mb-2">
                        <!--begin::Label-->
                        <label class="col-sm-3 col-form-label fw-bold fs-6">
                            <span>@Html.DisplayNameFor(model => model.ModifyNote)</span>
                        </label>
                        <!--end::Label-->
                        <!--begin::Col-->
                        <div class="col-sm-6 fv-row">

                            <textarea name="ModifyNote" class="form-control" required="required" style="height:100px"></textarea>
                            @Html.ValidationMessageFor(model => model.ModifyNote, "", new { @class = "text-danger" })
                        </div>
                        <!--end::Col-->
                    </div>
                    <!--end::Input group-->
                    <!--begin::Input group-->
                    <div class="row justify-content-center mb-2">
                        <!--begin::Label-->
                        <label class="col-sm-3 col-form-label fw-bold fs-6">
                            <span>@Html.DisplayNameFor(model => model.ModifiedAt)</span>
                        </label>
                        <!--end::Label-->
                        <!--begin::Col-->
                        <div class="col-sm-6 fv-row">
                            <input type="datetime-local" name="ModifiedAt" class="form-control" />
                            @Html.ValidationMessageFor(model => model.ModifiedAt, "", new { @class = "text-danger" })
                        </div>
                        <!--end::Col-->
                    </div>
                    <!--end::Input group-->
                    <!--begin::Input group-->
                    <div class="row justify-content-center mb-2 ">
                        <!--begin::Label-->
                        <label class="col-sm-3 col-form-label fw-bold fs-6">
                            <span>File</span>
                        </label>
                        <!--end::Label-->
                        <!--begin::Col-->
                        <div class="col-sm-6 fv-row">
                            <input type="file" name="FileUpload"
                                   accept=".pdf"
                                   formenctype="multipart/form-data"
                                   class="form-control" id="fileUpload"
                                   required="required" />
                            <a href="#" data-toggle="modal" data-target="#TestPlanPreviewModal">
                                Preview
                            </a>
                            <p id="noticeFileError" class="text-danger"></p>
                        </div>
                        <!--end::Col-->
                    </div>
                    <!--end::Input group-->
                    <!--begin::Action group-->
                    <div class="form-group">
                        <div class="col-md-offset-2" align="center">
                            <input type="submit" id="btnSubmitTestPlan" value="Create" class="btn btn-outline-primary" />
                            <input type="reset" value="Reset" class="btn btn-outline-primary" />
                        </div>
                    </div>
                    <div align="center">
                        <a href="@Url.Action("TestPlanIndex", "AdmTestPlan")">
                            <i class="fas fa-fw fa-arrow-circle-left"></i>
                            <span>Test Plan List</span>
                        </a>
                    </div>
                    <!--end::Action group-->
                </div>
                <!--end::Card body-->
            </div>
            <!--end::Post-->

        </div>
        <!--end::Content-->
    </div>
}

<!-- PDF file preview modal-->
<div class="modal fade ChartModal" id="TestPlanPreviewModal" tabindex="-1" role="dialog" aria-labelledby="TestPlanPreviewModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header ">
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <div align="center" id="TestPlanPreviewModalBody">
                    <iframe src="" id="FilePreviewSection" style="width:900px; height:800px"></iframe>

                </div>
            </div>
        </div>

    </div>
</div>
<script src="~/Assets/JS/MyJS/TestPlanModule/TestPlanCommonFuncs.js"></script>

ATEVersions_Management/ATEVersions_Management/Areas/Admin/Views/AdmTestPlan/TestPlanDetail.cshtml
@using ATEVersions_Management.Models.DTOModels
@model TestPlanDTO
@using ATEVersions_Management.Models.HelperModels
@{
    ViewBag.Title = "Detail: " + Model.ModelName + "_" + Model.TestPlanVersion;
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="form-horizontal row justify-content-center">
    <!--begin::Content -->
    <div class="content d-flex flex-column flex-column-fluid col-xl-6">
        <!--begin::Post-->
        <div class="card shadow d-flex flex-column-fluid ">
            <div class="card-header py-3">
                <h3 class="m-0 font-weight-bold text-primary">Test Plan Detail</h3>
            </div>
            <!--begin::Card body-->
            <div class="card-body border-top p-9">
                <!--begin::Display group-->
                <div class="row mb-2">
                    <!--begin::Label-->
                    <label class="col-lg-4 col-form-label fw-bold fs-6 border">
                        <span>@Html.DisplayNameFor(model => model.ModelName)</span>
                    </label>
                    <!--end::Label-->
                    <!--begin::Col-->
                    <div class="col-lg-8 col-form-label fv-row border border-left-primary">
                        @Html.DisplayFor(model => model.ModelName)
                    </div>
                    <!--end::Col-->
                </div>
                <!--end::Display group-->
                <!--begin::Display group-->
                <div class="row mb-2">
                    <!--begin::Label-->
                    <label class="col-lg-4 col-form-label fw-bold fs-6 border">
                        <span>@Html.DisplayNameFor(model => model.UserName)</span>
                    </label>
                    <!--end::Label-->
                    <!--begin::Col-->
                    <div class="col-lg-8 col-form-label fv-row border border-left-primary">
                        @Html.DisplayFor(model => model.UserName)
                    </div>
                    <!--end::Col-->
                </div>
                <!--end::Display group-->
                <!--begin::Display group-->
                <div class="row mb-2">
                    <!--begin::Label-->
                    <label class="col-lg-4 col-form-label fw-bold fs-6 border">
                        <span>@Html.DisplayNameFor(model => model.TestPlanVersion)</span>
                    </label>
                    <!--end::Label-->
                    <!--begin::Col-->
                    <div class="col-lg-8 col-form-label fv-row border border-left-primary">
                        @Html.DisplayFor(model => model.TestPlanVersion)
                    </div>
                    <!--end::Col-->
                </div>
                <!--end::Display group-->
                <!--begin::Display group-->
                <div class="row mb-2">
                    <!--begin::Label-->
                    <label class="col-lg-4 col-form-label fw-bold fs-6 border">
                        <span>@Html.DisplayNameFor(model => model.TestPlanVersion)</span>
                    </label>
                    <!--end::Label-->
                    <!--begin::Col-->
                    <div class="col-lg-8 col-form-label fv-row border border-left-primary">
                        @Html.DisplayFor(model => model.TestPlanVersion)
                    </div>
                    <!--end::Col-->
                </div>
                <!--end::Display group-->
                <!--begin::Display group-->
                <div class="row mb-2">
                    <!--begin::Label-->
                    <label class="col-lg-4 col-form-label fw-bold fs-6 border">
                        <span>@Html.DisplayNameFor(model => model.Author)</span>
                    </label>
                    <!--end::Label-->
                    <!--begin::Col-->
                    <div class="col-lg-8 col-form-label fv-row border border-left-primary">
                        @Html.DisplayFor(model => model.Author)
                    </div>
                    <!--end::Col-->
                </div>
                <!--end::Display group-->
                <!--begin::Display group-->
                <div class="row mb-2">
                    <!--begin::Label-->
                    <label class="col-lg-4 col-form-label fw-bold fs-6 border">
                        <span>@Html.DisplayNameFor(model => model.StoredDir)</span>
                    </label>
                    <!--end::Label-->
                    <!--begin::Col-->
                    <div class="col-lg-8 col-form-label fv-row border border-left-primary">
                        <a href="#" title="Preview"
                           data-toggle="modal" data-target="#TestPlanPreviewModal"
                           onclick="GetTestPlanFileData('@Model.StoredDir')">
                            <i class="fas fa-fw fa-file-pdf"></i>
                            <span id="preFileName"></span>
                        </a>
                    </div>
                    <!--end::Col-->
                </div>
                <!--end::Display group-->
                <!--begin::Display group-->
                <div class="row mb-2">
                    <!--begin::Label-->
                    <label class="col-lg-4 col-form-label fw-bold fs-6 border">
                        <span>@Html.DisplayNameFor(model => model.ModifiedAt)</span>
                    </label>
                    <!--end::Label-->
                    <!--begin::Col-->
                    <div class="col-lg-8 col-form-label fv-row border border-left-primary">
                        @Html.DisplayFor(model => model.ModifiedAt)
                    </div>
                    <!--end::Col-->
                </div>
                <!--end::Display group-->
                <!--begin::Display group-->
                <div class="row mb-2">
                    <!--begin::Label-->
                    <label class="col-lg-4 col-form-label fw-bold fs-6 border">
                        <span>@Html.DisplayNameFor(model => model.ModifyNote)</span>
                    </label>
                    <!--end::Label-->
                    <!--begin::Col-->
                    <div class="col-lg-8 col-form-label fv-row border border-left-primary">
                        <span class="breakLine">@Html.DisplayFor(model => model.ModifyNote)</span>
                    </div>
                    <!--end::Col-->
                </div>
                <!--end::Display group-->
                <!--begin::Display group-->
                <div class="row mb-2">
                    <!--begin::Label-->
                    <label class="col-lg-4 col-form-label fw-bold fs-6 border">
                        <span>@Html.DisplayNameFor(model => model.Status)</span>
                    </label>
                    <!--end::Label-->
                    <!--begin::Col-->
                    <div class="col-lg-8 col-form-label fv-row border border-left-primary">
                        @switch (Model.Status)
                        {
                            case 0:<span class="text-danger">Disable</span> break;
                            case 1: <span class="text-success">Enable</span>break;
                        }
                    </div>
                    <!--end::Col-->
                </div>
                <!--end::Display group-->
                <!--begin::Tracking section-->
                <h4 class="row mb-2 font-weight-bold text-primary border p-2">Tracking changes</h4>
                <!--end::Tracking section-->
                <!--begin::Display group-->
                <div class="row mb-2">
                    <!--begin::Label-->
                    <label class="col-lg-4 col-form-label fw-bold fs-6 border">
                        <span>@Html.DisplayNameFor(model => model.CreatedAt)</span>
                    </label>
                    <!--end::Label-->
                    <!--begin::Col-->
                    <div class="col-lg-8 col-form-label fv-row border border-left-primary">
                        @Html.DisplayFor(model => model.CreatedAt)
                    </div>
                    <!--end::Col-->
                </div>
                <!--end::Display group-->
                <!--begin::Display group-->
                <div class="row mb-2">
                    <!--begin::Label-->
                    <label class="col-lg-4 col-form-label fw-bold fs-6 border">
                        <span>@Html.DisplayNameFor(model => model.UpdatedAt)</span>
                    </label>
                    <!--end::Label-->
                    <!--begin::Col-->
                    <div class="col-lg-8 col-form-label fv-row border border-left-primary">
                        <span>@Html.DisplayFor(model => model.UpdatedAt)</span>
                    </div>
                    <!--end::Col-->
                </div>
                <!--end::Display group-->
                <!--begin::Display group-->
                <div class="row mb-2">
                    <!--begin::Label-->
                    <label class="col-lg-4 col-form-label fw-bold fs-6 border">
                        <span>@Html.DisplayNameFor(model => model.UpdatedBy)</span>
                    </label>
                    <!--end::Label-->
                    <!--begin::Col-->
                    <div class="col-lg-8 col-form-label fv-row border border-left-primary">
                        <span>@Html.DisplayFor(model => model.UpdatedBy)</span>
                    </div>
                    <!--end::Col-->
                </div>
                <!--end::Display group-->
                <!--begin::Action group-->
                <div align="center">
                    <a href="@Url.Action("TestPlanIndex", "AdmTestPlan")">
                        <i class="fas fa-fw fa-arrow-circle-left"></i>
                        <span>Test Plan List</span>
                    </a> |
                    @if (User.Identity.GetUserId() == Model.UserID)
                    {

                        <a href="@Url.Action("TestPlanEdit", "AdmTestPlan", new { id = Model.TestPlanID })">
                            <i class="fas fa-fw fa-pen-square"></i>
                            <span>Edit</span>
                        </a>
                    }

                </div>
                <!--end::Action group-->
            </div>
            <!--end::Card body-->
        </div>
        <!--end::Post-->

    </div>
    <!--end::Content-->
</div>

<!-- PDF file preview modal-->
<div class="modal fade ChartModal" id="TestPlanPreviewModal" tabindex="-1" role="dialog" aria-labelledby="TestPlanPreviewModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header ">
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <div align="center" id="TestPlanPreviewModalBody">
                    <iframe src="" id="FilePreviewSection" style="width:900px; height:800px"></iframe>

                </div>
            </div>
        </div>

    </div>
</div>

<script src="~/Assets/JS/MyJS/TestPlanModule/TestPlanCommonFuncs.js"></script>
<script>
    _filePath = '@Model.StoredDir';
    DisplayPreFileName(_filePath);
</script>