ATEVersions_Management/ATEVersions_Management/Areas/Admin/Controllers/AdmUserController.cs
using ATEVersions_Management.Models.ATEVersionModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using System.IO;
using System.Security.Principal;
using ATEVersions_Management.Models.HelperModels;
using static ATEVersions_Management.Models.HelperModels.ManualSelectors;
using ATEVersions_Management.Models.AccountModels;
using System.Web.Helpers;
using System.Web.Security;

namespace ATEVersions_Management.Areas.Admin.Controllers
{
    public class AdmUserController : DashboardController
    {
        readonly ATEVersionContext ateContext = new ATEVersionContext();
        // GET: Admin/User
        public ActionResult UserIndex()
        {
            List<USER> userList = ateContext.USERS.ToList();
            return View(userList);
        }
        // User detail view
        public ActionResult UserDetail(int id)
        {
            USER dtlUser = ateContext.USERS.Find(id);
            return View(dtlUser);
        }
        // Create user view
        public ActionResult UserCreate()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home", new { area = "" });
            }
            ViewBag.RoleSelector = new SelectList(ateContext.ROLES, "RoleID", "RoleName");            
            return View();
        }
        // POST: Create user action
        [HttpPost]
        public async Task<ActionResult> UserCreate(MyRegister rgsModel, USER user)
        {
            ViewBag.RoleSelector = new SelectList(ateContext.ROLES, "RoleID", "RoleName");            
            bool existUser = ateContext.USERS.Any(u => u.UserName == rgsModel.Username);
            string notify = "This username has been used, please choose another!";
            //
            try
            {
                if (!existUser)
                {
                    user.RoleID = rgsModel.RoleID;
                    user.UserName = rgsModel.Username;
                    user.FullName = rgsModel.Name;
                    string hashPw = Crypto.Hash(rgsModel.Password.Trim() + rgsModel.Username);
                    user.Password = hashPw;
                    user.Department = rgsModel.Department;
                    /*rgsUser.Avatar = "/Images/Samples/undraw_profile.svg";*/
                    user.Status = 1;
                    user.CreatedAt = DateTime.Now;
                    user.UpdatedAt = DateTime.Now;
                    user.UpdatedBy = rgsModel.Username + " | " + rgsModel.Name;
                    ateContext.USERS.Add(user);
                    ateContext.Configuration.ValidateOnSaveEnabled = false;                    
                    await ateContext.SaveChangesAsync();
                    //Finishing up
                    Notification.setFlash1s("Create user "+rgsModel.Username+" successfully","success");
                    return RedirectToAction("UserIndex");
                }                
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
                notify = "Error at: " + ex.Message;
            }
            //
            ViewBag.Notify = notify;
            return View(rgsModel);
        }
        // User edit view
        public ActionResult UserEdit(int id)
        {
            if (User.Identity.GetRoleName() == "Admin")
            {
                USER edtUser = ateContext.USERS.Find(id);
                ViewBag.RoleSelector = new SelectList(ateContext.ROLES, "RoleID", "RoleName");
                List<StatusSelector> statusSelectors = GetStatusSelectors();
                ViewBag.StatusSelector = new SelectList(statusSelectors, "StatusCode", "StatusValue");

                return View(edtUser);
            }
            return RedirectToAction("AdminIndex","Dasboard");
        }
        // User edit action
        [HttpPost]
        public async Task<ActionResult> UserEdit(USER user)
        {
            USER edtUser = ateContext.USERS.Find(user.UserID);
            ViewBag.RoleSelector = new SelectList(ateContext.ROLES, "RoleID", "RoleName");
            try
            {
                
                //infor change
                edtUser.RoleID = user.RoleID;
                edtUser.FullName = user.FullName;
                edtUser.Department = user.Department;
                edtUser.Email = user.Email;
                edtUser.PhoneNumber = user.PhoneNumber;
                edtUser.Status = user.Status;
                edtUser.UpdatedAt = DateTime.Now;
                edtUser.UpdatedBy = User.Identity.GetUserName() + " | " + User.Identity.GetName();
                
                await ateContext.SaveChangesAsync();

                Notification.setFlash1s("Edit user " + edtUser.UserName + " successfully", "success");
                return Redirect("~/Admin/AdmUser/UserDetail/" + edtUser.UserID);

            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                Console.WriteLine(ex.Message);

            }

            return View(user);
        }
        // Reset password view
        public ActionResult ResetPW(int userID)
        {
            if (User.Identity.GetRoleName() == "Admin")
            {
                USER user = ateContext.USERS.Find(userID);
                ViewBag.User = user;
                return View();
            }
            return RedirectToAction("AdminIndex", "Dasboard");
        }
        // POST: Reset password action
        [HttpPost]
        public async Task<ActionResult> ResetPW(int userID, MyResetPassword rpwModel)
        {
            USER user = ateContext.USERS.Find(userID);
            string hashPW = Crypto.Hash(rpwModel.NewPassword + user.UserName);
            
            //Change password            
            user.Password = hashPW;
            //Save to database
            await ateContext.SaveChangesAsync();
            //Finishing up
            Notification.setFlash("Reset password successfully!", "success");
                   
            return RedirectToAction("UserIndex");

        }

        #region UseLater
        /*
            // Upload image to Images folder 
            //image file handle
                if (user.FileUpload == null)
                {
                    edtUser.Avatar = edtUser.Avatar;
                }
                else
                {
                    string fileName = Path.GetFileNameWithoutExtension(user.FileUpload.FileName);
                    string extension = Path.GetExtension(user.FileUpload.FileName);
                    string folderLocate = "/Images/ImagesAvatar/";
                    fileName = DateTime.Now.ToString("dd-MM-yyyy") + "_" + fileName + extension;
                    edtUser.Avatar =  folderLocate + fileName;
                    fileName = Path.Combine(Server.MapPath("~" + folderLocate), fileName);
                    user.FileUpload.SaveAs(fileName);
                }
         */
        #endregion
    }
}

ATEVersions_Management/ATEVersions_Management/Areas/Admin/Views/AdmUser/UserCreate.cshtml
@using ATEVersions_Management.Models.AccountModels
@model MyRegister
@{
    ViewBag.Title = "Create User";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";

    IEnumerable<System.Web.Mvc.SelectListItem> RoleSelector = ViewBag.RoleSelector;
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xl-7 col-md-9">
                <div class="card o-hidden border-0 shadow-lg my-5 ">
                    <div class="card-header py-3">
                        <h3 class="m-0 font-weight-bold text-primary text-center">User Create</h3>                        
                    </div>
                    <div class="card-body p-3">
                        <!-- Nested Row within Card Body -->
                        
                        <div class="text-center">
                            <p class="text-danger">@ViewBag.Notify</p>
                        </div>
                        <form class="user">
                            <div class="form-group row ">
                                <!--begin::Col-->
                                <div class="col-sm-6 ">
                                    @Html.DropDownListFor(model => model.RoleID, RoleSelector, "-- Select role --", new { @class = "form-select" })
                                </div>
                                <!--end::Col-->
                                <div class="col-sm-6">

                                    @Html.EditorFor(model => model.Department, new { htmlAttributes = new { @class = "form-control form-control-user", placeholder = "Department" } })
                                    @Html.ValidationMessageFor(model => model.Department, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-sm-6 mb-3 mb-sm-0">

                                    @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control form-control-user upperText", placeholder = "Username" } })
                                    @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                                </div>
                                <div class="col-sm-6">

                                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control form-control-user", placeholder = "Full name" } })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-sm-6 mb-3 mb-sm-0">

                                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control form-control-user", placeholder = "Password" } })
                                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                                </div>
                                <div class="col-sm-6">
                                    @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control form-control-user", placeholder = "Confirm password" } })
                                    @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group row d-flex justify-content-center">
                                <div class="col-sm-4">
                                    <input type="submit" class="btn btn-primary btn-user btn-block" value="Create user" />                                   
                                </div>
                                <div class="col-sm-4">                                    
                                    <input type="reset" class="btn btn-primary btn-user btn-block" value="Reset" />
                                </div>
                            </div>
                            <hr>
                        </form>
                        <hr>
                        <div class="text-center">
                            <a href="@Url.Action("UserIndex","AdmUser")">
                                <i class="fas fa-arrow-circle-left"></i>
                                <span>User List</span>
                            </a>
                        </div>
                        
                    </div>
                </div>
            </div>

        </div>

    </div>
}

ATEVersions_Management/ATEVersions_Management/Areas/Admin/Views/AdmUser/UserDetail.cshtml
@model ATEVersions_Management.Models.ATEVersionModels.USER

@{
    ViewBag.Title = "User Detail";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="form-horizontal row justify-content-center">
    <!--begin::Content -->
    <div class="content d-flex flex-column flex-column-fluid col-xl-6">
        <!--begin::Post-->
        <div class="card shadow d-flex flex-column-fluid ">
            <div class="card-header py-3">
                <h3 class="m-0 font-weight-bold text-primary">User Detail Information</h3>
            </div>
            <!--begin::Card body-->
            <div class="card-body border-top p-9">
                <!--begin::Display group-->
                <div class="row mb-2">
                    <!--begin::Label-->
                    <label class="col-lg-4 col-form-label fw-bold fs-6 border">
                        <span>@Html.DisplayNameFor(model => model.ROLE.RoleName)</span>
                    </label>
                    <!--end::Label-->
                    <!--begin::Col-->
                    <div class="col-lg-8 col-form-label fv-row border border-left-primary">
                        <span class="text-bg-info text-gray-100 fw-bold p-1 rounded-2">@Model.ROLE.RoleName</span>
                    </div>
                    <!--end::Col-->
                </div>
                <!--end::Display group-->
                <!--begin::Display group-->
                <div class="row mb-2">
                    <!--begin::Label-->
                    <label class="col-lg-4 col-form-label fw-bold fs-6 border">
                        <span>@Html.DisplayNameFor(model => model.UserName)</span>
                    </label>
                    <!--end::Label-->
                    <!--begin::Col-->
                    <div class="col-lg-8 col-form-label fv-row border border-left-primary">
                        <span class="text-bg-primary text-gray-100 fw-bold p-1 rounded-2">@Model.UserName</span>
                    </div>
                    <!--end::Col-->
                </div>
                <!--end::Display group-->
                <!--begin::Display group-->
                <div class="row mb-2">
                    <!--begin::Label-->
                    <label class="col-lg-4 col-form-label fw-bold fs-6 border">
                        <span>@Html.DisplayNameFor(model => model.FullName)</span>
                    </label>
                    <!--end::Label-->
                    <!--begin::Col-->
                    <div class="col-lg-8 col-form-label fv-row border border-left-primary">
                        @Html.DisplayFor(model => model.FullName)
                    </div>
                    <!--end::Col-->
                </div>
                <!--end::Display group-->
                <!--begin::Display group-->
                <div class="row mb-2">
                    <!--begin::Label-->
                    <label class="col-lg-4 col-form-label fw-bold fs-6 border">
                        <span>@Html.DisplayNameFor(model => model.Department)</span>
                    </label>
                    <!--end::Label-->
                    <!--begin::Col-->
                    <div class="col-lg-8 col-form-label fv-row border border-left-primary">
                        @Html.DisplayFor(model => model.Department)
                    </div>
                    <!--end::Col-->
                </div>
                <!--end::Display group-->
                <!--begin::Display group-->
                <div class="row mb-2">
                    <!--begin::Label-->
                    <label class="col-lg-4 col-form-label fw-bold fs-6 border">
                        <span>@Html.DisplayNameFor(model => model.Email)</span>
                    </label>
                    <!--end::Label-->
                    <!--begin::Col-->
                    <div class="col-lg-8 col-form-label fv-row border border-left-primary">
                        @Html.DisplayFor(model => model.Email)
                    </div>
                    <!--end::Col-->
                </div>
                <!--end::Display group-->
                <!--begin::Display group-->
                <div class="row mb-2">
                    <!--begin::Label-->
                    <label class="col-lg-4 col-form-label fw-bold fs-6 border">
                        <span>@Html.DisplayNameFor(model => model.PhoneNumber)</span>
                    </label>
                    <!--end::Label-->
                    <!--begin::Col-->
                    <div class="col-lg-8 col-form-label fv-row border border-left-primary">
                        @Html.DisplayFor(model => model.PhoneNumber)
                    </div>
                    <!--end::Col-->
                </div>
                <!--end::Display group-->
                <!--begin::Display group-->
                <div class="row mb-2">
                    <!--begin::Label-->
                    <label class="col-lg-4 col-form-label fw-bold fs-6 border">
                        <span>@Html.DisplayNameFor(model => model.Status)</span>
                    </label>
                    <!--end::Label-->
                    <!--begin::Col-->
                    <div class="col-lg-8 col-form-label fv-row border border-left-primary">
                        @switch (Model.Status)
                        {
                            case 0:<span class="text-danger">Disable</span> break;
                            case 1: <span class="text-success">Enable</span>break;
                        }
                    </div>
                    <!--end::Col-->
                </div>
                <!--end::Display group-->
                <!--begin::Tracking section-->
                <h4 class="row mb-2 font-weight-bold text-primary border p-2">Tracking changes</h4>
                <!--end::Tracking section-->
                <!--begin::Display group-->
                <div class="row mb-2">
                    <!--begin::Label-->
                    <label class="col-lg-4 col-form-label fw-bold fs-6 border">
                        <span>@Html.DisplayNameFor(model => model.CreatedAt)</span>
                    </label>
                    <!--end::Label-->
                    <!--begin::Col-->
                    <div class="col-lg-8 col-form-label fv-row border border-left-primary">
                        @Html.DisplayFor(model => model.CreatedAt)
                    </div>
                    <!--end::Col-->
                </div>
                <!--end::Display group-->
                <!--begin::Display group-->
                <div class="row mb-2">
                    <!--begin::Label-->
                    <label class="col-lg-4 col-form-label fw-bold fs-6 border">
                        <span>@Html.DisplayNameFor(model => model.UpdatedAt)</span>
                    </label>
                    <!--end::Label-->
                    <!--begin::Col-->
                    <div class="col-lg-8 col-form-label fv-row border border-left-primary">
                        <span>@Html.DisplayFor(model => model.UpdatedAt)</span>
                    </div>
                    <!--end::Col-->
                </div>
                <!--end::Display group-->
                <!--begin::Display group-->
                <div class="row mb-2">
                    <!--begin::Label-->
                    <label class="col-lg-4 col-form-label fw-bold fs-6 border">
                        <span>@Html.DisplayNameFor(model => model.UpdatedBy)</span>
                    </label>
                    <!--end::Label-->
                    <!--begin::Col-->
                    <div class="col-lg-8 col-form-label fv-row border border-left-primary">
                        <span>@Html.DisplayFor(model => model.UpdatedBy)</span>
                    </div>
                    <!--end::Col-->
                </div>
                <!--end::Display group-->
                <!--begin::Action group-->
                <div align="center">
                    <a href="@Url.Action("UserIndex", "AdmUser")">
                        <i class="fas fa-fw fa-arrow-circle-left"></i>
                        <span>User List</span>
                    </a> |
                    <a href="@Url.Action("UserEdit", "AdmUser", new { id = Model.UserID })">
                        <i class="fas fa-fw fa-pen-square"></i>
                        <span>Edit</span>
                    </a> |
                    <a href="@Url.Action("ResetPW", "AdmUser", new { userID = Model.UserID })">
                        <i class="fas fa-fw fa-user-lock"></i>
                        <span>Reset password</span>
                    </a>
                </div>
                <!--end::Action group-->
            </div>
            <!--end::Card body-->
        </div>
        <!--end::Post-->

    </div>
    <!--end::Content-->
</div>

ATEVersions_Management/ATEVersions_Management/Areas/Admin/Views/AdmUser/UserEdit.cshtml
@model ATEVersions_Management.Models.ATEVersionModels.USER
@using ATEVersions_Management.Models.HelperModels
@{
    ViewBag.Title = "Edit User";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";

    IEnumerable<System.Web.Mvc.SelectListItem> RoleSelector = ViewBag.RoleSelector;
    IEnumerable<System.Web.Mvc.SelectListItem> StatusSelector = ViewBag.StatusSelector;
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal row justify-content-center">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.UserID)
        <!--begin::Content -->
        <div class="content d-flex flex-column flex-column-fluid col-xl-6">
            <!--begin::Post-->
            <div class="card shadow d-flex flex-column-fluid ">
                <div class="card-header py-3">
                    <h3 class="m-0 font-weight-bold text-primary">Update User Information</h3>
                </div>
                <!--begin::Card body-->
                <div class="card-body border-top p-9">
                    <!--begin::Display group-->
                    <div class="row mb-2">
                        <!--begin::Label-->
                        <label class="col-lg-4 col-form-label fw-bold fs-6">
                            <span>@Html.DisplayNameFor(model => model.UserName)</span>
                        </label>
                        <!--end::Label-->
                        <!--begin::Col-->
                        <div class="col-lg-8 col-form-label fv-row ">
                            <span class="text-bg-primary text-gray-100 fw-bold p-1 rounded-2">@Model.UserName</span>
                        </div>
                        <!--end::Col-->
                    </div>
                    <!--end::Display group-->
                    <!--begin::Input group-->
                    <div class="row mb-2">
                        <!--begin::Label-->
                        <label class="col-lg-4 col-form-label fw-bold fs-6">
                            <span>@Html.DisplayNameFor(model => model.FullName)</span>
                        </label>
                        <!--end::Label-->
                        <!--begin::Col-->
                        <div class="col-lg-8 fv-row">
                            @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
                        </div>
                        <!--end::Col-->
                    </div>
                    <!--end::Input group-->
                    <!--begin::Input group-->
                    <div class="row mb-2">
                        <!--begin::Label-->
                        <label class="col-lg-4 col-form-label fw-bold fs-6">
                            <span>@Html.DisplayNameFor(model => model.ROLE.RoleName)</span>
                        </label>
                        <!--end::Label-->
                        <!--begin::Col-->
                        <div class="col-lg-8 col-form-label fv-row">
                            @Html.DropDownListFor(model => model.RoleID, RoleSelector, new { @class = "form-select" })
                        </div>
                        <!--end::Col-->
                    </div>
                    <!--end::Input group-->
                    <!--begin::Input group-->
                    <div class="row mb-2">
                        <!--begin::Label-->
                        <label class="col-lg-4 col-form-label fw-bold fs-6">
                            <span>@Html.DisplayNameFor(model => model.Department)</span>
                        </label>
                        <!--end::Label-->
                        <!--begin::Col-->
                        <div class="col-lg-8 fv-row">
                            @Html.EditorFor(model => model.Department, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Department, "", new { @class = "text-danger" })
                        </div>
                        <!--end::Col-->
                    </div>
                    <!--end::Input group-->
                    <!--begin::Input group-->
                    <div class="row mb-2">
                        <!--begin::Label-->
                        <label class="col-lg-4 col-form-label fw-bold fs-6">
                            <span>@Html.DisplayNameFor(model => model.Email)</span>
                        </label>
                        <!--end::Label-->
                        <!--begin::Col-->
                        <div class="col-lg-8 fv-row">
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                        <!--end::Col-->
                    </div>
                    <!--end::Input group-->
                    <!--begin::Input group-->
                    <div class="row mb-2">
                        <!--begin::Label-->
                        <label class="col-lg-4 col-form-label fw-bold fs-6">
                            <span>@Html.DisplayNameFor(model => model.PhoneNumber)</span>
                        </label>
                        <!--end::Label-->
                        <!--begin::Col-->
                        <div class="col-lg-8 fv-row">
                            @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                        </div>
                        <!--end::Col-->
                    </div>
                    <!--end::Input group-->
                    <!--begin::Input group-->
                    <div class="row mb-2">
                        <!--begin::Label-->
                        <label class="col-lg-4 col-form-label fw-bold fs-6">
                            <span>@Html.DisplayNameFor(model => model.Status)</span>
                        </label>
                        <!--end::Label-->
                        <!--begin::Col-->
                        <div class="col-lg-8 fv-row">
                            @if (Model.ROLE.RoleName != "Admin")
                            {
                                @Html.DropDownListFor(model => model.Status, StatusSelector, new { @class = "form-select" })
                            }
                            else
                            {
                                <span class="text-success p-1">Enable</span>
                                @Html.HiddenFor(model => model.Status)
                            }

                        </div>
                        <!--end::Col-->
                    </div>
                    <!--end::Input group-->
                    <!--begin::Action group-->
                    <div class="form-group">
                        <div class="col-md-offset-2" align="center">
                            <input type="submit" value="Update" class="btn btn-outline-primary" />
                            <input type="reset" value="Reset" class="btn btn-outline-primary" />
                        </div>
                    </div>
                    <div align="center">
                        <a href="@Url.Action("UserIndex", "AdmUser")">
                            <i class="fas fa-fw fa-arrow-circle-left"></i>
                            <span>User List</span>
                        </a>
                    </div>
                    <!--end::Action group-->
                </div>
                <!--end::Card body-->
            </div>
            <!--end::Post-->


        </div>
        <!--end::Content-->
    </div>
}


<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#blah').attr('src', e.target.result);
            };

            reader.readAsDataURL(input.files[0]);
        }
    }
</script>