ATEVersions_Management/ATEVersions_Management/Areas/Admin/Controllers/AdmProgramController.cs
using ATEVersions_Management.Models.ATEVersionModels;
using ATEVersions_Management.Models.DAOModels;
using ATEVersions_Management.Models.HelperModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace ATEVersions_Management.Areas.Admin.Controllers
{
    public class AdmProgramController : DashboardController
    {
        readonly ATEVersionContext ateContext = new ATEVersionContext();
        // GET: Admin/AdProgram
        [Route("Admin/Program/Index")]
        public ActionResult ProgramIndex()
        {
            List<PROGRAM> prgList = ateContext.PROGRAMs.Where(p => p.Status != 0).ToList();
            return View(prgList);
        }

        // Detail of program infor
        public ActionResult ProgramDetail(int id)
        {
            PROGRAM detailProgram = ateContext.PROGRAMs.Find(id);

            return View(detailProgram);
        }

        // Create new program info
        public ActionResult ProgramCreate()
        {
            if (User.Identity.GetRoleName() == "Admin" || User.Identity.GetRoleName() == "Preparer")
            {                                
                ViewBag.listProjectType = new SelectList(ATEVersionsDAO.GET_ListProjectType());
                return View();
            }
            return RedirectToAction("ProgramIndex");
        }

        [HttpPost]
        public async Task<ActionResult> ProgramCreate(PROGRAM createProgram)
        {
            if (!ExistProgram(createProgram.ProgramID, createProgram.ModelName))
            {
                try
                {
                    createProgram.Status = 1;
                    createProgram.CreatedAt = DateTime.Now;
                    createProgram.UpdatedAt = DateTime.Now;
                    createProgram.UpdatedBy = User.Identity.GetUserName() + " | " + User.Identity.GetName();
                    ateContext.PROGRAMs.Add(createProgram);
                    await ateContext.SaveChangesAsync();
                    Notification.setFlash1s("Create info for"+ createProgram.ModelName +" successfully!","success");
                    return RedirectToAction("ProgramIndex");
                }
                catch (Exception ex)
                {
                    ViewBag.Error = ex;
                    Console.WriteLine(ex.ToString());
                }
            }
            Notification.setFlash1s(createProgram.ModelName+" is already exist!", "danger");
            return View();
        }
       
        // Update program info
        public ActionResult ProgramEdit(int id)
        {
            if (User.Identity.GetRoleName() == "Admin" || User.Identity.GetRoleName() == "Preparer")
            {
                PROGRAM edtProgram = ateContext.PROGRAMs.Find(id);
                ViewBag.listProjectType = new SelectList(ATEVersionsDAO.GET_ListProjectType());
                return View(edtProgram);
            }
            return RedirectToAction("ProgramIndex");
        }

        [HttpPost]
        public async Task<ActionResult> ProgramEdit(PROGRAM editProgram)
        {
            PROGRAM edtProgram = ateContext.PROGRAMs.Find(editProgram.ProgramID);
            try
            {
                if (!ExistProgram(editProgram.ProgramID, editProgram.ModelName))
                {
                    edtProgram.ProgramName = editProgram.ProgramName;
                    edtProgram.ModelName = editProgram.ModelName;
                    edtProgram.DevelopTool = editProgram.DevelopTool;
                    edtProgram.ProjectType = editProgram.ProjectType;
                    edtProgram.UpdatedAt = DateTime.Now;
                    edtProgram.UpdatedBy = User.Identity.GetUserName() + " | " + User.Identity.GetName();
                    await ateContext.SaveChangesAsync();

                    Notification.setFlash1s("Edit " + edtProgram.ModelName + " successfully!", "success");
                    return Redirect("~/Admin/AdmProgram/ProgramDetail/" + editProgram.ProgramID);
                }
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex;
                Console.WriteLine(ex.ToString());
                Notification.setFlash1s("Fail to update program " + editProgram.ModelName + "!\n" + "Error: " + ex.ToString(), "danger");
            }
            Notification.setFlash1s(editProgram.ModelName + " is already exist!", "danger");
            return View(editProgram);
        }
        // Delete program info
        [HttpPost]
        public async Task<ActionResult> ProgramDelete(int id)
        {
            if (User.Identity.GetRoleName() == "Admin" || User.Identity.GetRoleName() == "Preparer")
            {
                PROGRAM dltProgram = ateContext.PROGRAMs.Find(id);
                try
                {
                   
                    dltProgram.Status = 0;
                    dltProgram.UpdatedAt = DateTime.Now;
                    dltProgram.UpdatedBy = User.Identity.GetUserName() + " | " + User.Identity.GetName();

                    await ateContext.SaveChangesAsync();

                }
                catch (Exception ex)
                {
                    Console.WriteLine("Error: " + ex);
                }                
            }
            return RedirectToAction("ProgramIndex");
        } 
        // To version list by program id
        public ActionResult VerProgList(int prgId)
        {            

            return Redirect("~/Admin/AdmVersion/VersionIndex/"+ prgId);
        }
        #region Hepler
        public bool ExistProgram(int? prgId , string model)
        {
            PROGRAM tmp = ateContext.PROGRAMs.FirstOrDefault(p => p.ModelName.ToLower() == model.ToLower());
            if(prgId.HasValue)
                tmp = ateContext.PROGRAMs.FirstOrDefault(p => p.ProgramID != prgId && p.ModelName.ToLower() == model.ToLower());
            return tmp != null;
        }
        #endregion
    }
}

ATEVersions_Management/ATEVersions_Management/Areas/Admin/Views/AdmProgram/ProgramCreate.cshtml
@using ATEVersions_Management.Models.ATEVersionModels
@model PROGRAM

@{
    ViewBag.Title = "Program Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    //
    SelectList listProjectType = ViewBag.listProjectType as SelectList;
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal row justify-content-center">
    
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <!--begin::Content -->
    <div class="content d-flex flex-column flex-column-fluid col-xl-6">       
        <!--begin::Post-->
        <div class="card shadow d-flex flex-column-fluid ">
            <div class="card-header py-3">
                <h3 class="m-0 font-weight-bold text-primary">New Program Information</h3>
            </div>
            <!--begin::Card body-->
            <div class="card-body border-top p-9">
                <!--begin::Input group-->
                <div class="row mb-2">
                    <!--begin::Label-->
                    <label class="col-sm-4 col-form-label fw-bold fs-6">
                        <span>@Html.DisplayNameFor(model => model.ModelName)</span>
                    </label>
                    <!--end::Label-->
                    <!--begin::Col-->
                    <div class="col-sm-8 fv-row">
                        @Html.EditorFor(model => model.ModelName, new { htmlAttributes = new { @class = "form-control upperText", required = "required" } })
                        @Html.ValidationMessageFor(model => model.ModelName, "", new { @class = "text-danger col-form-label" })
                    </div>
                    <!--end::Col-->
                </div>
                <!--end::Input group-->
                <!--begin::Input group-->
                <div class="row mb-2">
                    <!--begin::Label-->
                    <label class="col-sm-4 col-form-label fw-bold fs-6">
                        <span>@Html.DisplayNameFor(model => model.ProgramName)</span>
                    </label>
                    <!--end::Label-->
                    <!--begin::Col-->
                    <div class="col-sm-8 fv-row">
                        @Html.EditorFor(model => model.ProgramName, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                        @Html.ValidationMessageFor(model => model.ProgramName, "", new { @class = "text-danger" })
                    </div>
                    <!--end::Col-->
                </div>
                <!--end::Input group-->
                <!--begin::Input group-->
                <div class="row mb-2">
                    <!--begin::Label-->
                    <label class="col-lg-4 col-form-label fw-bold fs-6">
                        <span>@Html.DisplayNameFor(model => model.ProjectType)</span>
                    </label>
                    <!--end::Label-->
                    <!--begin::Col-->
                    <div class="col-lg-8 fv-row">
                        @Html.DropDownListFor(model => model.ProjectType, listProjectType, "--- Select type ---", htmlAttributes: new { @class = "form-select", @id = "" })
                        @Html.ValidationMessageFor(model => model.ProjectType, "", new { @class = "text-danger" })
                    </div>
                    <!--end::Col-->
                </div>
                <!--end::Input group-->
                <!--begin::Input group-->
                <div class="row mb-2">
                    <!--begin::Label-->
                    <label class="col-sm-4 col-form-label fw-bold fs-6">
                        <span>@Html.DisplayNameFor(model => model.DevelopTool)</span>
                    </label>
                    <!--end::Label-->
                    <!--begin::Col-->
                    <div class="col-sm-8 fv-row">
                        @Html.EditorFor(model => model.DevelopTool, new { htmlAttributes = new { @class = "form-control", Value = "C++ Builder", required = "required" } })
                        @Html.ValidationMessageFor(model => model.DevelopTool, "", new { @class = "text-danger" })
                    </div>
                    <!--end::Col-->
                </div>
                <!--end::Input group-->
                <!--begin::Action group-->
                <div class="form-group">
                    <div class="col-md-offset-2" align="center">
                        <input type="submit" value="Create" class="btn btn-outline-primary" />
                        <input type="reset" value="Reset" class="btn btn-outline-primary" />
                    </div>
                </div>
                <div align="center">
                    <a href="@Url.Action("ProgramIndex", "AdmProgram")">
                        <i class="fas fa-fw fa-arrow-circle-left"></i>
                        <span>Program List</span>
                    </a>
                </div>
                <!--end::Action group-->
            </div>
            <!--end::Card body-->
        </div>
        <!--end::Post-->
       
    </div>
    <!--end::Content-->
</div>
}
<div>
    @ViewBag.Error
</div>

ATEVersions_Management/ATEVersions_Management/Areas/Admin/Views/AdmProgram/ProgramDetail.cshtml
@model ATEVersions_Management.Models.ATEVersionModels.PROGRAM
@using ATEVersions_Management.Models.HelperModels
@{
    ViewBag.Title = "Detail: " + Model.ProgramName;
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="form-horizontal row justify-content-center">   
    <!--begin::Content -->
    <div class="content d-flex flex-column flex-column-fluid col-xl-6">
        <!--begin::Post-->
        <div class="card shadow d-flex flex-column-fluid ">
            <div class="card-header py-3">
                <h3 class="m-0 font-weight-bold text-primary">Program Detail Information</h3>
            </div>
            <!--begin::Card body-->
            <div class="card-body border-top p-9">
                <!--begin::Display group-->
                <div class="row mb-2">
                    <!--begin::Label-->
                    <label class="col-lg-4 col-form-label fw-bold fs-6 border">
                        <span>@Html.DisplayNameFor(model => model.ProgramID)</span>
                    </label>
                    <!--end::Label-->
                    <!--begin::Col-->
                    <div class="col-lg-8 col-form-label fv-row border border-left-primary">
                        @Html.DisplayFor(model => model.ProgramID)
                    </div>
                    <!--end::Col-->
                </div>
                <!--end::Display group-->
                <!--begin::Display group-->
                <div class="row mb-2">
                    <!--begin::Label-->
                    <label class="col-lg-4 col-form-label fw-bold fs-6 border">
                        <span>@Html.DisplayNameFor(model => model.ProgramName)</span>
                    </label>
                    <!--end::Label-->
                    <!--begin::Col-->
                    <div class="col-lg-8 col-form-label fv-row border border-left-primary">
                        @Html.DisplayFor(model => model.ProgramName)
                    </div>
                    <!--end::Col-->
                </div>
                <!--end::Display group-->
                <!--begin::Display group-->
                <div class="row mb-2">
                    <!--begin::Label-->
                    <label class="col-lg-4 col-form-label fw-bold fs-6 border">
                        <span>@Html.DisplayNameFor(model => model.ModelName)</span>
                    </label>
                    <!--end::Label-->
                    <!--begin::Col-->
                    <div class="col-lg-8 col-form-label fv-row border border-left-primary">
                        @Html.DisplayFor(model => model.ModelName)
                    </div>
                    <!--end::Col-->
                </div>
                <!--end::Display group-->
                <!--begin::Display group-->
                <div class="row mb-2">
                    <!--begin::Label-->
                    <label class="col-lg-4 col-form-label fw-bold fs-6 border">
                        <span>@Html.DisplayNameFor(model => model.ProjectType)</span>
                    </label>
                    <!--end::Label-->
                    <!--begin::Col-->
                    <div class="col-lg-8 col-form-label fv-row border border-left-primary">
                        @Html.DisplayFor(model => model.ProjectType)
                    </div>
                    <!--end::Col-->
                </div>
                <!--end::Display group-->
                <!--begin::Display group-->
                <div class="row mb-2">
                    <!--begin::Label-->
                    <label class="col-lg-4 col-form-label fw-bold fs-6 border">
                        <span>@Html.DisplayNameFor(model => model.DevelopTool)</span>
                    </label>
                    <!--end::Label-->
                    <!--begin::Col-->
                    <div class="col-lg-8 col-form-label fv-row border border-left-primary">
                        @Html.DisplayFor(model => model.DevelopTool)
                    </div>
                    <!--end::Col-->
                </div>
                <!--end::Display group-->
                <!--begin::Display group-->
                <div class="row mb-2">
                    <!--begin::Label-->
                    <label class="col-lg-4 col-form-label fw-bold fs-6 border">
                        <span>@Html.DisplayNameFor(model => model.Status)</span>
                    </label>
                    <!--end::Label-->
                    <!--begin::Col-->
                    <div class="col-lg-8 col-form-label fv-row border border-left-primary">
                        @switch (Model.Status)
                        {
                            case 0:<span class="text-danger">Disable</span> break;
                            case 1: <span class="text-success">Enable</span>break;
                        }
                    </div>
                    <!--end::Col-->
                </div>
                <!--end::Display group-->
                <!--begin::Tracking section-->
                <h4 class="row mb-2 font-weight-bold text-primary border p-2">Tracking changes</h4>
                <!--end::Tracking section-->
                <!--begin::Display group-->
                <div class="row mb-2">
                    <!--begin::Label-->
                    <label class="col-lg-4 col-form-label fw-bold fs-6 border">
                        <span>@Html.DisplayNameFor(model => model.CreatedAt)</span>
                    </label>
                    <!--end::Label-->
                    <!--begin::Col-->
                    <div class="col-lg-8 col-form-label fv-row border border-left-primary">
                        @Html.DisplayFor(model => model.CreatedAt)
                    </div>
                    <!--end::Col-->
                </div>
                <!--end::Display group-->
                <!--begin::Display group-->
                <div class="row mb-2">
                    <!--begin::Label-->
                    <label class="col-lg-4 col-form-label fw-bold fs-6 border">
                        <span>@Html.DisplayNameFor(model => model.UpdatedAt)</span>
                    </label>
                    <!--end::Label-->
                    <!--begin::Col-->
                    <div class="col-lg-8 col-form-label fv-row border border-left-primary">
                        <span>@Html.DisplayFor(model => model.UpdatedAt)</span>
                    </div>
                    <!--end::Col-->
                </div>
                <!--end::Display group-->
                <!--begin::Display group-->
                <div class="row mb-2">
                    <!--begin::Label-->
                    <label class="col-lg-4 col-form-label fw-bold fs-6 border">
                        <span>@Html.DisplayNameFor(model => model.UpdatedBy)</span>
                    </label>
                    <!--end::Label-->
                    <!--begin::Col-->
                    <div class="col-lg-8 col-form-label fv-row border border-left-primary">
                        <span>@Html.DisplayFor(model => model.UpdatedBy)</span>
                    </div>
                    <!--end::Col-->
                </div>
                <!--end::Display group-->
                <!--begin::Action group-->
                <div align="center">
                    <a href="@Url.Action("ProgramIndex", "AdmProgram")">
                        <i class="fas fa-fw fa-arrow-circle-left"></i>
                        <span>Program List</span>
                    </a> |
                    @if (User.Identity.GetRoleName() != "Checker" && User.Identity.GetRoleName() != "Approver")
                    {
                        <a href="@Url.Action("ProgramEdit", "AdmProgram", new { id = Model.ProgramID })">
                            <i class="fas fa-fw fa-pen-square"></i>
                            <span>Edit</span>
                        </a>
                    }
                    |
                    <a href="@Url.Action("VersionIndex", "AdmVersion", new {prgId = Model.ProgramID})">
                        <span>Version List</span>
                        <i class="fas fa-fw fa-arrow-circle-right"></i>
                    </a>
                </div>
                <!--end::Action group-->
            </div>
            <!--end::Card body-->
        </div>
        <!--end::Post-->

    </div>
    <!--end::Content-->
</div>

ATEVersions_Management/ATEVersions_Management/Areas/Admin/Views/AdmProgram/ProgramEdit.cshtml
@model ATEVersions_Management.Models.ATEVersionModels.PROGRAM

@{
    ViewBag.Title = "Edit: "+Model.ProgramName;
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    //
    SelectList listProjectType = ViewBag.listProjectType as SelectList;
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal row justify-content-center">

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ProgramID)
    <!--begin::Content -->
    <div class="content d-flex flex-column flex-column-fluid col-xl-6">
        <!--begin::Post-->
        <div class="card shadow d-flex flex-column-fluid ">
            <div class="card-header py-3">
                <h3 class="m-0 font-weight-bold text-primary">Update Program Information</h3>
            </div>
            <!--begin::Card body-->
            <div class="card-body border-top p-9">
                <!--begin::Input group-->
                <div class="row mb-2">
                    <!--begin::Label-->
                    <label class="col-lg-4 col-form-label fw-bold fs-6">
                        <span>@Html.DisplayNameFor(model => model.ModelName)</span>
                    </label>
                    <!--end::Label-->
                    <!--begin::Col-->
                    <div class="col-lg-8 fv-row">
                        @Html.EditorFor(model => model.ModelName, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                        @Html.ValidationMessageFor(model => model.ModelName, "", new { @class = "text-danger" })
                    </div>
                    <!--end::Col-->
                </div>
                <!--end::Input group-->
                <!--begin::Input group-->
                <div class="row mb-2">
                    <!--begin::Label-->
                    <label class="col-lg-4 col-form-label fw-bold fs-6">
                        <span>@Html.DisplayNameFor(model => model.ProgramName)</span>
                    </label>
                    <!--end::Label-->
                    <!--begin::Col-->
                    <div class="col-lg-8 fv-row">
                        @Html.EditorFor(model => model.ProgramName, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                        @Html.ValidationMessageFor(model => model.ProgramName, "", new { @class = "text-danger" })
                    </div>
                    <!--end::Col-->
                </div>
                <!--end::Input group-->
                <!--begin::Input group-->
                <div class="row mb-2">
                    <!--begin::Label-->
                    <label class="col-lg-4 col-form-label fw-bold fs-6">
                        <span>@Html.DisplayNameFor(model => model.ProjectType)</span>
                    </label>
                    <!--end::Label-->
                    <!--begin::Col-->
                    <div class="col-lg-8 fv-row">
                        @Html.DropDownListFor(model => model.ProjectType, listProjectType, "--- Select type ---", htmlAttributes: new { @class = "form-select", @id = "" })
                        @Html.ValidationMessageFor(model => model.ProjectType, "", new { @class = "text-danger" })
                    </div>
                    <!--end::Col-->
                </div>
                <!--end::Input group-->
                <!--begin::Input group-->
                <div class="row mb-2">
                    <!--begin::Label-->
                    <label class="col-lg-4 col-form-label fw-bold fs-6">
                        <span>@Html.DisplayNameFor(model => model.DevelopTool)</span>
                    </label>
                    <!--end::Label-->
                    <!--begin::Col-->
                    <div class="col-lg-8 fv-row">
                        @Html.EditorFor(model => model.DevelopTool, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                        @Html.ValidationMessageFor(model => model.DevelopTool, "", new { @class = "text-danger" })
                    </div>
                    <!--end::Col-->
                </div>
                <!--end::Input group-->
                <!--begin::Action group-->
                <div class="form-group">
                    <div class="col-md-offset-2" align="center">
                        <input type="submit" value="Update" class="btn btn-outline-primary" />
                        <input type="reset" value="Reset" class="btn btn-outline-primary" />
                    </div>
                </div>
                <div align="center">
                    <a href="@Url.Action("ProgramIndex", "AdmProgram")">
                        <i class="fas fa-fw fa-arrow-circle-left"></i>
                        <span>Program List</span>
                    </a>
                </div>
                <!--end::Action group-->
            </div>
            <!--end::Card body-->
        </div>
        <!--end::Post-->

    </div>
    <!--end::Content-->
</div>
}

ATEVersions_Management/ATEVersions_Management/Areas/Admin/Views/AdmProgram/ProgramIndex.cshtml
@using ATEVersions_Management.Models.ATEVersionModels
@model IEnumerable<PROGRAM>
@using ATEVersions_Management.Models.HelperModels
@{
    ViewBag.Title = "Program Index";
    //Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    Layout = "~/Views/Shared/_LayoutFiiTheme.cshtml";
}

<!-- DataTables -->
<div class="card shadow mb-4">

    <div class="card-header py-3">
        <h3 class="m-0 font-weight-bold text-primary">Program Index</h3>

        @if (User.Identity.GetRoleName() != "Checker" && User.Identity.GetRoleName() != "Approver")
        {
            <div style="padding-top:10px">
                @Html.ActionLink("Create New", "ProgramCreate", "", new { @class = "btn btn-outline-primary" })
            </div>
        }

    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered text-black" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>

                        <th>
                            @Html.DisplayNameFor(model => model.ModelName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.ProgramName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.DevelopTool)
                        </th>
                        <th>
                            Action
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>

                            <td>
                                @Html.DisplayFor(modelItem => item.ModelName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ProgramName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.DevelopTool)
                            </td>

                            <td>
                                <a href="@Url.Action("ProgramDetail", "AdmProgram", new { id = item.ProgramID })">
                                    <i class="fas fa-fw fa-info-circle"></i>
                                </a>
                                @if (User.Identity.GetRoleName() != "Checker" && User.Identity.GetRoleName() != "Approver")
                                {
                                    <a href="@Url.Action("ProgramEdit", "AdmProgram", new { id = item.ProgramID })">
                                        <i class="fas fa-fw fa-pen-square"></i>
                                    </a>
                                    <a href="#" data-toggle="modal" data-target="#deleteModal" onclick="DltConfirm(@item.ProgramID,'@item.ProgramName')">
                                        <i class="fas fa-fw fa-trash"></i>
                                    </a>

                                }

                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- begin :: layout test -->

<!-- end :: layout test -->
<!-- Delete Modal-->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action="@Url.Action("ProgramDelete", "AdmProgram")" method="post">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Are you sure want to delete this record?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <input type="hidden" name="id" class="idValModal" />

                    <label>Program ID: <span class="idTxtModal"></span></label><br />
                    <label>Program name: <span class="nameTxtModal"></span> </label>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <input type="submit" value="Delete" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

<script src="~/Assets/JS/AdminJS/helperIndexModals.js"></script>